# Generated by Django 5.2.4 on 2025-07-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recepies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepies_name', models.CharField(db_index=True, max_length=100)),
                ('recepies_description', models.TextField()),
                ('recepies_image', models.ImageField(upload_to='recepie_images/')),
            ],
        ),
    ]
