# Generated by Django 5.2.4 on 2025-07-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
    ]
